### ISSUE TITLE
Text not highlighting correctly 

### ISSUE THREAD

**Issue by msya** [daniel-zahariev/jquery-textntags#1]
Hello, 

I use your auto complete and it's great. I just encountered a bug. Suppose I have written a paragraph and I use the autocomplete at the end, everything works fine there. However, when I go in the middle of the paragraph and use the autocomplete, the higlighting and markup are off.

**Comment by daniel-zahariev** [comment]
Can you attach a screenshot to make better sense of the issue.

**Comment by msya** [comment]
https://github.com/msya/images/blob/master/autcomplete.png

**Comment by msya** [comment]
Is my screenshot helpful? Would you be able to fix this issue?

**Comment by daniel-zahariev** [comment]
Yes, it's helpful. I was able to reproduce it and hopefully tomorrow i'll push a fix.

**Comment by msya** [comment]
I was looking for an update this past friday. This would be really helpful to me. I want to know if you are planning to release it today or tomorrow. Thank you.

**Comment by daniel-zahariev** [comment]
This is fixed now.
