### ISSUE TITLE
How to Can I change tag text and How to Can I show all tag List.

### ISSUE THREAD

**Issue by mesutcakir** [daniel-zahariev/jquery-textntags#14]
we use trigger "$". After entering a trigger value than I want show list of all the tag list.

**Comment by daniel-zahariev** [comment]
Intended use of the plugin is with very large list of tags and that's why showing the full list of tags isn't supported.
When do you want to change the tag text - when it's added in the text, after the data is loaded by the plugin, ... ?

**Comment by mesutcakir** [comment]
Okay, thank you.

I've got a solution to filter by removing tiny.
