### ISSUE TITLE
Deactivate beautifier

### ISSUE THREAD

**Issue by nicolasalcina** [daniel-zahariev/jquery-textntags#23]
Hello,
I got a problem when I hide the beautifier (no usefull for me),
before I type a character the cursor in the textarea is very small seems to have an unzoom.
After typing a character all is normal
when I grow the font-size of the textarea the cursor can be normal but for the first char the font-size come again normally and high
In the better case I don't want to make a script to change the font-size after the first char.
Did I miss a CSS property that unzoom ?
PS:  sorry for the bad english
EDIT: only in IE 9/10/11 works normally in FF/Chrome/Opera/Safari

**Comment by daniel-zahariev** [comment]
How do you hide the beautifier? I would recommend with `style="visibility:hidden"`.

**Comment by nicolasalcina** [comment]
I put a display: none on ".textntags-wrapper .textntags-beautifier > div"
visibility:hidden change nothing for me :'(
so I do a script:

> function updateBeautifier() {  
>             if($.browser.msie && getBeautifiedText() === '&#38;shy;') {
>                 elEditor.css('font-size', '50px');
>             } else if(calinda.browser.msie) {
>                 elEditor.css('font-size', '12px');
>             }
>             elBeautifier.find('div').html(getBeautifiedText());
>             elEditor.css('height', elBeautifier.outerHeight() + 'px');
>        }

**Comment by daniel-zahariev** [comment]
Did you manage to resolve your case?

**Comment by nicolasalcina** [comment]
Yes with the script, that's why I close the issue
I preffered another method, it's maybe not your plugin fault
